name: Build Linux ARM64
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Main:
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup build environment
        uses: ./.github/workflows/shared/setup-build-environment

      - name: Set publish flag
        shell: bash
        run: |
          if [[ "$GIT_TAG_NAME" = v* ]]; then
            echo "PUBLISH_ENABLED=true" >> "$GITHUB_ENV"
          else
            echo "PUBLISH_ENABLED=false" >> "$GITHUB_ENV"
          fi

      - name: Build Linux ARM64 app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          IS_CONTINUOUS_INTEGRATION: 1
          BUILD_SEQUENCIAL: 1
          PUBLISH_ENABLED: ${{ env.PUBLISH_ENABLED }}
        shell: bash
        run: |
          export npm_config_arch=arm64
          export npm_config_target_arch=arm64
          source "${GITHUB_WORKSPACE}/.github/scripts/retry.sh"
          retry yarn install

          cd packages/app-desktop
          npm pkg set 'build.linux.artifactName'='Joplin-${version}-${arch}.${ext}'
          npm pkg delete 'build.linux.target'
          npm pkg set 'build.linux.target[0].target'='AppImage'
          npm pkg set 'build.linux.target[0].arch[0]'='arm64'
          npm pkg set 'build.linux.target[1].target'='deb'
          npm pkg set 'build.linux.target[1].arch[0]'='arm64'

          if [[ "$PUBLISH_ENABLED" == "true" ]]; then
            echo "Building and publishing Linux ARM64 application..."
            USE_HARD_LINKS=false yarn dist --linux --arm64
          else
            echo "Building Linux ARM64 application without publishing..."
            USE_HARD_LINKS=false yarn dist --linux --arm64 --publish=never
          fi